export {Main} from "./Main"
export {NotFound} from "./NotFound"
export {Brand} from "./Brand"
export {Client} from "./Clients"
export {Contacts} from "./Contacts"
export {Newes} from  "./News"
export {PageNews} from "./PageNews"
export {Catalog2} from "./Catalog2"